# _config.yml
title: My Learning Blog
description: Record my path of growth ✨
theme: minima
url: "https://sunkuangdong.github.io"

# information about the author
author:
  name: Kuangdong Sun
  email: sunkuangdong@gmail.com & ksun5@depaul.edu

# navigation bar
nav:
  - Home: /
  - About: /about
  - Contact: /contact

# pagination
paginate: 10
permalink: /:categories/:title.html

# categories
categories:
  - Distributed System
  - Cloud Computing
  - Big Data
  - Machine Learning
  - Deep Learning
  - Computer Vision
  - Natural Language Processing